name: 步步宝

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/HH97108/99.git ~/99
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/99
          npm install
          npm install cron
          npm install request
      - name: '运行 【AAB】'
        run: |
          cd ~/99   
          node Task/aaa.js
