# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青浏览赚

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0 29 2 *'
  watch:
    types: youth_gain
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_START: ${{ secrets.YOUTH_START }}
      YOUTH_END: ${{ secrets.YOUTH_END }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青浏览赚】'
        if: env.YOUTH_START
        run: |
          node Task/youth_banner.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          YOUTH_START: ${{ secrets.YOUTH_START }}
          YOUTH_END: ${{ secrets.YOUTH_END }}
